[versions]
kotlin = "2.1.0"

spock = "2.4-M4-groovy-4.0"

[libraries]
# core dependencies
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }

# test dependencies
spock-core = { group = "org.spockframework", name = "spock-core", version.ref = "spock" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
kotlin = ['kotlin', 'kotlin-stdlib']
spock = ['spock-core']